apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret/harbor-registry-external-secret.yaml
  - resource/deploy.yaml
  - resource/service.yaml
  - resource/http-route.yaml
