apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: son-blog-base-route
  namespace: blog
spec:
  parentRefs:
    - name: web-gateway
      namespace: nginx-gateway
      sectionName: http-wildcard
    - name: web-gateway
      namespace: nginx-gateway
      sectionName: https-wildcard
  hostnames:
    - blog-base.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: son-blog-base-service
          port: 80
